### PR TITLE
Adim Rspec

### PR DESCRIPTION
**Pull request by Ewiseman**

### CODE REVIEW

**Comment by Ewiseman** [comment]
Having some trouble with this assignment.  Below is the error I am receiving on Rspec 

```
Visiting profiles sign in as admin shows profile
     Failure/Error: visit user_path(@user)
     ActionView::Template::Error:
       undefined method `comment_path' for #<#<Class:0x007fd9c9ade418>:0x007fd9cb109e18>
```
Let me know your thoughts when you have time. 

Thank you!

**Comment by eliotsykes** [comment]
This part of the error message suggests that the non-existent method `comment_path` is being called in a template somewhere

```
ActionView::Template::Error:
       undefined method `comment_path' for #<#<Class:0x007fd9c9ade418>:0x007fd9cb109e18>
```

Try searching the app's files for where `comment_path` is being used. Sublime's "Find in Files..." (Cmd+Shift+F) is good for this. 

Once you've found where `comment_path` is being called, run `rake routes` and see if you can identify why the comment_path method doesn't seem to exist. Let me know how you get on.

**Comment by Ewiseman** [comment]
Thank you for the hint.  I did what you mentioned and searched for ```comment_path``` within my application and found nothing.  That's why I'm puzzled.  If there is no ```comment_path`` then how can I correct the route?  

I am assuming there is no ```comment_path``` based off the rake route search.  

Not really sure where to go from here.  I also checked out the bloc repo file and it *appears* that we have the same code.

**Comment by Ewiseman** [comment]
Figured it out.  Sorry for the bogus question.  Didn't read the full question.  

Thank you!

Eric

**Pull request closed without merging**
